{
  "a1.2xlarge" = { cores = 8; memory = 16384; allowsEbsOptimized = true; supportsNVMe = false;};
  "a1.4xlarge" = { cores = 16; memory = 32768; allowsEbsOptimized = true; supportsNVMe = false;};
  "a1.large" = { cores = 2; memory = 4096; allowsEbsOptimized = true; supportsNVMe = false;};
  "a1.medium" = { cores = 1; memory = 2048; allowsEbsOptimized = true; supportsNVMe = false;};
  "a1.metal" = { allowsEbsOptimized = true; cores = 16; memory = 32768; supportsNVMe = true; };
  "a1.xlarge" = { cores = 4; memory = 8192; allowsEbsOptimized = true; supportsNVMe = false;};
  "c1.medium" = { cores = 2; memory = 1740; allowsEbsOptimized = false; supportsNVMe = false;};
  "c1.xlarge" = { cores = 8; memory = 7168; allowsEbsOptimized = true; supportsNVMe = false;};
  "c3.2xlarge" = { cores = 8; memory = 15360; allowsEbsOptimized = true; supportsNVMe = false;};
  "c3.4xlarge" = { cores = 16; memory = 30720; allowsEbsOptimized = true; supportsNVMe = false;};
  "c3.8xlarge" = { cores = 32; memory = 61440; allowsEbsOptimized = false; supportsNVMe = false;};
  "c3.large" = { cores = 2; memory = 3840; allowsEbsOptimized = false; supportsNVMe = false;};
  "c3.xlarge" = { cores = 4; memory = 7680; allowsEbsOptimized = true; supportsNVMe = false;};
  "c4.2xlarge" = { cores = 8; memory = 15360; allowsEbsOptimized = true; supportsNVMe = false;};
  "c4.4xlarge" = { cores = 16; memory = 30720; allowsEbsOptimized = true; supportsNVMe = false;};
  "c4.8xlarge" = { cores = 36; memory = 61440; allowsEbsOptimized = true; supportsNVMe = false;};
  "c4.large" = { cores = 2; memory = 3840; allowsEbsOptimized = true; supportsNVMe = false;};
  "c4.xlarge" = { cores = 4; memory = 7680; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 98304; supportsNVMe = false; };
  "c5.18xlarge" = { cores = 72; memory = 147456; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 196608; supportsNVMe = false; };
  "c5.2xlarge" = { cores = 8; memory = 16384; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5.4xlarge" = { cores = 16; memory = 32768; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5.9xlarge" = { cores = 36; memory = 73728; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5.large" = { cores = 2; memory = 4096; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5.metal" = { allowsEbsOptimized = true; cores = 96; memory = 196608; supportsNVMe = false; };
  "c5.xlarge" = { cores = 4; memory = 8192; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5a.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 98304; supportsNVMe = true; };
  "c5a.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 131072; supportsNVMe = true; };
  "c5a.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 196608; supportsNVMe = true; };
  "c5a.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 16384; supportsNVMe = true; };
  "c5a.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 32768; supportsNVMe = true; };
  "c5a.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 65536; supportsNVMe = true; };
  "c5a.large" = { allowsEbsOptimized = true; cores = 2; memory = 4096; supportsNVMe = true; };
  "c5a.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 8192; supportsNVMe = true; };
  "c5ad.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 98304; supportsNVMe = true; };
  "c5ad.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 131072; supportsNVMe = true; };
  "c5ad.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 196608; supportsNVMe = true; };
  "c5ad.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 16384; supportsNVMe = true; };
  "c5ad.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 32768; supportsNVMe = true; };
  "c5ad.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 65536; supportsNVMe = true; };
  "c5ad.large" = { allowsEbsOptimized = true; cores = 2; memory = 4096; supportsNVMe = true; };
  "c5ad.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 8192; supportsNVMe = true; };
  "c5d.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 98304; supportsNVMe = true; };
  "c5d.18xlarge" = { cores = 72; memory = 147456; allowsEbsOptimized = true; supportsNVMe = true;};
  "c5d.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 196608; supportsNVMe = true; };
  "c5d.2xlarge" = { cores = 8; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "c5d.4xlarge" = { cores = 16; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "c5d.9xlarge" = { cores = 36; memory = 73728; allowsEbsOptimized = true; supportsNVMe = true;};
  "c5d.large" = { cores = 2; memory = 4096; allowsEbsOptimized = true; supportsNVMe = true;};
  "c5d.metal" = { allowsEbsOptimized = true; cores = 96; memory = 196608; supportsNVMe = true; };
  "c5d.xlarge" = { cores = 4; memory = 8192; allowsEbsOptimized = true; supportsNVMe = true;};
  "c5n.18xlarge" = { cores = 72; memory = 196608; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5n.2xlarge" = { cores = 8; memory = 21504; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5n.4xlarge" = { cores = 16; memory = 43008; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5n.9xlarge" = { cores = 36; memory = 98304; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5n.large" = { cores = 2; memory = 5376; allowsEbsOptimized = true; supportsNVMe = false;};
  "c5n.metal" = { allowsEbsOptimized = true; cores = 72; memory = 196608; supportsNVMe = false; };
  "c5n.xlarge" = { cores = 4; memory = 10752; allowsEbsOptimized = true; supportsNVMe = false;};
  "c6g.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 98304; supportsNVMe = false; };
  "c6g.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 131072; supportsNVMe = false; };
  "c6g.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 16384; supportsNVMe = false; };
  "c6g.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 32768; supportsNVMe = false; };
  "c6g.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 65536; supportsNVMe = false; };
  "c6g.large" = { allowsEbsOptimized = true; cores = 2; memory = 4096; supportsNVMe = false; };
  "c6g.medium" = { allowsEbsOptimized = true; cores = 1; memory = 2048; supportsNVMe = false; };
  "c6g.metal" = { allowsEbsOptimized = true; cores = 64; memory = 131072; supportsNVMe = false; };
  "c6g.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 8192; supportsNVMe = false; };
  "c6gd.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 98304; supportsNVMe = true; };
  "c6gd.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 131072; supportsNVMe = true; };
  "c6gd.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 16384; supportsNVMe = true; };
  "c6gd.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 32768; supportsNVMe = true; };
  "c6gd.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 65536; supportsNVMe = true; };
  "c6gd.large" = { allowsEbsOptimized = true; cores = 2; memory = 4096; supportsNVMe = true; };
  "c6gd.medium" = { allowsEbsOptimized = true; cores = 1; memory = 2048; supportsNVMe = true; };
  "c6gd.metal" = { allowsEbsOptimized = true; cores = 64; memory = 131072; supportsNVMe = true; };
  "c6gd.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 8192; supportsNVMe = true; };
  "c6gn.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 98304; supportsNVMe = false; };
  "c6gn.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 131072; supportsNVMe = false; };
  "c6gn.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 16384; supportsNVMe = false; };
  "c6gn.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 32768; supportsNVMe = false; };
  "c6gn.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 65536; supportsNVMe = false; };
  "c6gn.large" = { allowsEbsOptimized = true; cores = 2; memory = 4096; supportsNVMe = false; };
  "c6gn.medium" = { allowsEbsOptimized = true; cores = 1; memory = 2048; supportsNVMe = false; };
  "c6gn.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 8192; supportsNVMe = false; };
  "cc2.8xlarge" = { cores = 32; memory = 61952; allowsEbsOptimized = false; supportsNVMe = false;};
  "cr1.8xlarge" = { cores = 32; memory = 249856; allowsEbsOptimized = true; supportsNVMe = false;};
  "d2.2xlarge" = { cores = 8; memory = 62464; allowsEbsOptimized = true; supportsNVMe = false;};
  "d2.4xlarge" = { cores = 16; memory = 124928; allowsEbsOptimized = true; supportsNVMe = false;};
  "d2.8xlarge" = { cores = 36; memory = 249856; allowsEbsOptimized = true; supportsNVMe = false;};
  "d2.xlarge" = { cores = 4; memory = 31232; allowsEbsOptimized = true; supportsNVMe = false;};
  "d3.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 65536; supportsNVMe = false; };
  "d3.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 131072; supportsNVMe = false; };
  "d3.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = false; };
  "d3.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 32768; supportsNVMe = false; };
  "d3en.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = false; };
  "d3en.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = false; };
  "d3en.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 65536; supportsNVMe = false; };
  "d3en.6xlarge" = { allowsEbsOptimized = true; cores = 24; memory = 98304; supportsNVMe = false; };
  "d3en.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = false; };
  "d3en.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = false; };
  "f1.16xlarge" = { cores = 64; memory = 999424; allowsEbsOptimized = true; supportsNVMe = true;};
  "f1.2xlarge" = { cores = 8; memory = 124928; allowsEbsOptimized = true; supportsNVMe = true;};
  "f1.4xlarge" = { cores = 16; memory = 249856; allowsEbsOptimized = true; supportsNVMe = true;};
  "g2.2xlarge" = { cores = 8; memory = 15360; allowsEbsOptimized = true; supportsNVMe = false;};
  "g2.8xlarge" = { cores = 32; memory = 61440; allowsEbsOptimized = false; supportsNVMe = false;};
  "g3.16xlarge" = { cores = 64; memory = 499712; allowsEbsOptimized = true; supportsNVMe = false;};
  "g3.4xlarge" = { cores = 16; memory = 124928; allowsEbsOptimized = true; supportsNVMe = false;};
  "g3.8xlarge" = { cores = 32; memory = 249856; allowsEbsOptimized = true; supportsNVMe = false;};
  "g3s.xlarge" = { cores = 4; memory = 31232; allowsEbsOptimized = true; supportsNVMe = false;};
  "g4ad.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "g4ad.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 65536; supportsNVMe = true; };
  "g4ad.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = true; };
  "g4dn.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = true; };
  "g4dn.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "g4dn.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = true; };
  "g4dn.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 65536; supportsNVMe = true; };
  "g4dn.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = true; };
  "g4dn.metal" = { allowsEbsOptimized = true; cores = 96; memory = 393216; supportsNVMe = true; };
  "g4dn.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = true; };
  "h1.16xlarge" = { cores = 64; memory = 262144; allowsEbsOptimized = true; supportsNVMe = false;};
  "h1.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = false;};
  "h1.4xlarge" = { cores = 16; memory = 65536; allowsEbsOptimized = true; supportsNVMe = false;};
  "h1.8xlarge" = { cores = 32; memory = 131072; allowsEbsOptimized = true; supportsNVMe = false;};
  "hs1.8xlarge" = { cores = 17; memory = 119808; allowsEbsOptimized = true; supportsNVMe = false;};
  "i2.2xlarge" = { cores = 8; memory = 62464; allowsEbsOptimized = true; supportsNVMe = false;};
  "i2.4xlarge" = { cores = 16; memory = 124928; allowsEbsOptimized = true; supportsNVMe = false;};
  "i2.8xlarge" = { cores = 32; memory = 249856; allowsEbsOptimized = false; supportsNVMe = false;};
  "i2.xlarge" = { cores = 4; memory = 31232; allowsEbsOptimized = true; supportsNVMe = false;};
  "i3.16xlarge" = { cores = 64; memory = 499712; allowsEbsOptimized = true; supportsNVMe = true;};
  "i3.2xlarge" = { cores = 8; memory = 62464; allowsEbsOptimized = true; supportsNVMe = true;};
  "i3.4xlarge" = { cores = 16; memory = 124928; allowsEbsOptimized = true; supportsNVMe = true;};
  "i3.8xlarge" = { cores = 32; memory = 249856; allowsEbsOptimized = true; supportsNVMe = true;};
  "i3.large" = { cores = 2; memory = 15616; allowsEbsOptimized = true; supportsNVMe = true;};
  "i3.metal" = { cores = 72; memory = 524288; allowsEbsOptimized = true; supportsNVMe = true;};
  "i3.xlarge" = { cores = 4; memory = 31232; allowsEbsOptimized = true; supportsNVMe = true;};
  "i3en.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 393216; supportsNVMe = true; };
  "i3en.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "i3en.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 65536; supportsNVMe = true; };
  "i3en.3xlarge" = { allowsEbsOptimized = true; cores = 12; memory = 98304; supportsNVMe = true; };
  "i3en.6xlarge" = { allowsEbsOptimized = true; cores = 24; memory = 196608; supportsNVMe = true; };
  "i3en.large" = { allowsEbsOptimized = true; cores = 2; memory = 16384; supportsNVMe = true; };
  "i3en.metal" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "i3en.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 32768; supportsNVMe = true; };
  "inf1.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 196608; supportsNVMe = false; };
  "inf1.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 16384; supportsNVMe = false; };
  "inf1.6xlarge" = { allowsEbsOptimized = true; cores = 24; memory = 49152; supportsNVMe = false; };
  "inf1.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 8192; supportsNVMe = false; };
  "m1.large" = { cores = 2; memory = 7680; allowsEbsOptimized = true; supportsNVMe = false;};
  "m1.medium" = { cores = 1; memory = 3840; allowsEbsOptimized = false; supportsNVMe = false;};
  "m1.small" = { cores = 1; memory = 1740; allowsEbsOptimized = false; supportsNVMe = false;};
  "m1.xlarge" = { cores = 4; memory = 15360; allowsEbsOptimized = true; supportsNVMe = false;};
  "m2.2xlarge" = { cores = 4; memory = 35020; allowsEbsOptimized = true; supportsNVMe = false;};
  "m2.4xlarge" = { cores = 8; memory = 70041; allowsEbsOptimized = true; supportsNVMe = false;};
  "m2.xlarge" = { cores = 2; memory = 17510; allowsEbsOptimized = false; supportsNVMe = false;};
  "m3.2xlarge" = { cores = 8; memory = 30720; allowsEbsOptimized = true; supportsNVMe = false;};
  "m3.large" = { cores = 2; memory = 7680; allowsEbsOptimized = false; supportsNVMe = false;};
  "m3.medium" = { cores = 1; memory = 3840; allowsEbsOptimized = false; supportsNVMe = false;};
  "m3.xlarge" = { cores = 4; memory = 15360; allowsEbsOptimized = true; supportsNVMe = false;};
  "m4.10xlarge" = { cores = 40; memory = 163840; allowsEbsOptimized = true; supportsNVMe = false;};
  "m4.16xlarge" = { cores = 64; memory = 262144; allowsEbsOptimized = true; supportsNVMe = false;};
  "m4.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = false;};
  "m4.4xlarge" = { cores = 16; memory = 65536; allowsEbsOptimized = true; supportsNVMe = false;};
  "m4.large" = { cores = 2; memory = 8192; allowsEbsOptimized = true; supportsNVMe = false;};
  "m4.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = true; supportsNVMe = false;};
  "m5.12xlarge" = { cores = 48; memory = 196608; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5.24xlarge" = { cores = 96; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5.4xlarge" = { cores = 16; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5.large" = { cores = 2; memory = 8192; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5.metal" = { cores = 96; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5a.12xlarge" = { cores = 48; memory = 196608; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5a.24xlarge" = { cores = 96; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5a.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5a.4xlarge" = { cores = 16; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5a.large" = { cores = 2; memory = 8192; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5a.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5ad.12xlarge" = { cores = 48; memory = 196608; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5ad.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "m5ad.24xlarge" = { cores = 96; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5ad.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5ad.4xlarge" = { cores = 16; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5ad.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = true; };
  "m5ad.large" = { cores = 2; memory = 8192; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5ad.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5d.12xlarge" = { cores = 48; memory = 196608; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5d.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "m5d.24xlarge" = { cores = 96; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5d.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5d.4xlarge" = { cores = 16; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5d.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = true; };
  "m5d.large" = { cores = 2; memory = 8192; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5d.metal" = { cores = 96; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5d.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "m5dn.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = true; };
  "m5dn.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "m5dn.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 393216; supportsNVMe = true; };
  "m5dn.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = true; };
  "m5dn.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 65536; supportsNVMe = true; };
  "m5dn.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = true; };
  "m5dn.large" = { allowsEbsOptimized = true; cores = 2; memory = 8192; supportsNVMe = true; };
  "m5dn.metal" = { allowsEbsOptimized = true; cores = 96; memory = 393216; supportsNVMe = true; };
  "m5dn.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = true; };
  "m5n.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = true; };
  "m5n.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "m5n.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 393216; supportsNVMe = true; };
  "m5n.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = true; };
  "m5n.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 65536; supportsNVMe = true; };
  "m5n.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = true; };
  "m5n.large" = { allowsEbsOptimized = true; cores = 2; memory = 8192; supportsNVMe = true; };
  "m5n.metal" = { allowsEbsOptimized = true; cores = 96; memory = 393216; supportsNVMe = true; };
  "m5n.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = true; };
  "m5zn.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = false; };
  "m5zn.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = false; };
  "m5zn.3xlarge" = { allowsEbsOptimized = true; cores = 12; memory = 49152; supportsNVMe = false; };
  "m5zn.6xlarge" = { allowsEbsOptimized = true; cores = 24; memory = 98304; supportsNVMe = false; };
  "m5zn.large" = { allowsEbsOptimized = true; cores = 2; memory = 8192; supportsNVMe = false; };
  "m5zn.metal" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = false; };
  "m5zn.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = false; };
  "m6g.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = false; };
  "m6g.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = false; };
  "m6g.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = false; };
  "m6g.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 65536; supportsNVMe = false; };
  "m6g.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = false; };
  "m6g.large" = { allowsEbsOptimized = true; cores = 2; memory = 8192; supportsNVMe = false; };
  "m6g.medium" = { allowsEbsOptimized = true; cores = 1; memory = 4096; supportsNVMe = false; };
  "m6g.metal" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = false; };
  "m6g.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = false; };
  "m6gd.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 196608; supportsNVMe = true; };
  "m6gd.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "m6gd.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = true; };
  "m6gd.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 65536; supportsNVMe = true; };
  "m6gd.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 131072; supportsNVMe = true; };
  "m6gd.large" = { allowsEbsOptimized = true; cores = 2; memory = 8192; supportsNVMe = true; };
  "m6gd.medium" = { allowsEbsOptimized = true; cores = 1; memory = 4096; supportsNVMe = true; };
  "m6gd.metal" = { allowsEbsOptimized = true; cores = 64; memory = 262144; supportsNVMe = true; };
  "m6gd.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = true; };
  "mac1.metal" = { allowsEbsOptimized = true; cores = 12; memory = 32768; supportsNVMe = true; };
  "p2.16xlarge" = { cores = 64; memory = 786432; allowsEbsOptimized = true; supportsNVMe = false;};
  "p2.8xlarge" = { cores = 32; memory = 499712; allowsEbsOptimized = true; supportsNVMe = false;};
  "p2.xlarge" = { cores = 4; memory = 62464; allowsEbsOptimized = true; supportsNVMe = false;};
  "p3.16xlarge" = { cores = 64; memory = 499712; allowsEbsOptimized = true; supportsNVMe = false;};
  "p3.2xlarge" = { cores = 8; memory = 62464; allowsEbsOptimized = true; supportsNVMe = false;};
  "p3.8xlarge" = { cores = 32; memory = 249856; allowsEbsOptimized = true; supportsNVMe = false;};
  "p3dn.24xlarge" = { cores = 96; memory = 786432; allowsEbsOptimized = true; supportsNVMe = false;};
  "p4d.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 1179648; supportsNVMe = true; };
  "r3.2xlarge" = { cores = 8; memory = 62464; allowsEbsOptimized = true; supportsNVMe = false;};
  "r3.4xlarge" = { cores = 16; memory = 124928; allowsEbsOptimized = true; supportsNVMe = false;};
  "r3.8xlarge" = { cores = 32; memory = 249856; allowsEbsOptimized = false; supportsNVMe = false;};
  "r3.large" = { cores = 2; memory = 15616; allowsEbsOptimized = false; supportsNVMe = false;};
  "r3.xlarge" = { cores = 4; memory = 31232; allowsEbsOptimized = true; supportsNVMe = false;};
  "r4.16xlarge" = { cores = 64; memory = 499712; allowsEbsOptimized = true; supportsNVMe = false;};
  "r4.2xlarge" = { cores = 8; memory = 62464; allowsEbsOptimized = true; supportsNVMe = false;};
  "r4.4xlarge" = { cores = 16; memory = 124928; allowsEbsOptimized = true; supportsNVMe = false;};
  "r4.8xlarge" = { cores = 32; memory = 249856; allowsEbsOptimized = true; supportsNVMe = false;};
  "r4.large" = { cores = 2; memory = 15616; allowsEbsOptimized = true; supportsNVMe = false;};
  "r4.xlarge" = { cores = 4; memory = 31232; allowsEbsOptimized = true; supportsNVMe = false;};
  "r5.12xlarge" = { cores = 48; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5.24xlarge" = { cores = 96; memory = 786432; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5.2xlarge" = { cores = 8; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5.4xlarge" = { cores = 16; memory = 131072; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5.large" = { cores = 2; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5.metal" = { cores = 96; memory = 786432; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5.xlarge" = { cores = 4; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5a.12xlarge" = { cores = 48; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5a.24xlarge" = { cores = 96; memory = 786432; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5a.2xlarge" = { cores = 8; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5a.4xlarge" = { cores = 16; memory = 131072; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5a.large" = { cores = 2; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5a.xlarge" = { cores = 4; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5ad.12xlarge" = { cores = 48; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5ad.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = true; };
  "r5ad.24xlarge" = { cores = 96; memory = 786432; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5ad.2xlarge" = { cores = 8; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5ad.4xlarge" = { cores = 16; memory = 131072; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5ad.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = true; };
  "r5ad.large" = { cores = 2; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5ad.xlarge" = { cores = 4; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5b.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 393216; supportsNVMe = true; };
  "r5b.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = true; };
  "r5b.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "r5b.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 65536; supportsNVMe = true; };
  "r5b.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 131072; supportsNVMe = true; };
  "r5b.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = true; };
  "r5b.large" = { allowsEbsOptimized = true; cores = 2; memory = 16384; supportsNVMe = true; };
  "r5b.metal" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "r5b.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 32768; supportsNVMe = true; };
  "r5d.12xlarge" = { cores = 48; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5d.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = true; };
  "r5d.24xlarge" = { cores = 96; memory = 786432; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5d.2xlarge" = { cores = 8; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5d.4xlarge" = { cores = 16; memory = 131072; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5d.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = true; };
  "r5d.large" = { cores = 2; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5d.metal" = { cores = 96; memory = 786432; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5d.xlarge" = { cores = 4; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
  "r5dn.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 393216; supportsNVMe = true; };
  "r5dn.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = true; };
  "r5dn.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "r5dn.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 65536; supportsNVMe = true; };
  "r5dn.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 131072; supportsNVMe = true; };
  "r5dn.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = true; };
  "r5dn.large" = { allowsEbsOptimized = true; cores = 2; memory = 16384; supportsNVMe = true; };
  "r5dn.metal" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "r5dn.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 32768; supportsNVMe = true; };
  "r5n.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 393216; supportsNVMe = true; };
  "r5n.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = true; };
  "r5n.24xlarge" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "r5n.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 65536; supportsNVMe = true; };
  "r5n.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 131072; supportsNVMe = true; };
  "r5n.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = true; };
  "r5n.large" = { allowsEbsOptimized = true; cores = 2; memory = 16384; supportsNVMe = true; };
  "r5n.metal" = { allowsEbsOptimized = true; cores = 96; memory = 786432; supportsNVMe = true; };
  "r5n.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 32768; supportsNVMe = true; };
  "r6g.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 393216; supportsNVMe = false; };
  "r6g.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = false; };
  "r6g.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 65536; supportsNVMe = false; };
  "r6g.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 131072; supportsNVMe = false; };
  "r6g.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = false; };
  "r6g.large" = { allowsEbsOptimized = true; cores = 2; memory = 16384; supportsNVMe = false; };
  "r6g.medium" = { allowsEbsOptimized = true; cores = 1; memory = 8192; supportsNVMe = false; };
  "r6g.metal" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = false; };
  "r6g.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 32768; supportsNVMe = false; };
  "r6gd.12xlarge" = { allowsEbsOptimized = true; cores = 48; memory = 393216; supportsNVMe = true; };
  "r6gd.16xlarge" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = true; };
  "r6gd.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 65536; supportsNVMe = true; };
  "r6gd.4xlarge" = { allowsEbsOptimized = true; cores = 16; memory = 131072; supportsNVMe = true; };
  "r6gd.8xlarge" = { allowsEbsOptimized = true; cores = 32; memory = 262144; supportsNVMe = true; };
  "r6gd.large" = { allowsEbsOptimized = true; cores = 2; memory = 16384; supportsNVMe = true; };
  "r6gd.medium" = { allowsEbsOptimized = true; cores = 1; memory = 8192; supportsNVMe = true; };
  "r6gd.metal" = { allowsEbsOptimized = true; cores = 64; memory = 524288; supportsNVMe = true; };
  "r6gd.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 32768; supportsNVMe = true; };
  "t1.micro" = { cores = 1; memory = 627; allowsEbsOptimized = false; supportsNVMe = false;};
  "t2.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = false; supportsNVMe = false;};
  "t2.large" = { cores = 2; memory = 8192; allowsEbsOptimized = false; supportsNVMe = false;};
  "t2.medium" = { cores = 2; memory = 4096; allowsEbsOptimized = false; supportsNVMe = false;};
  "t2.micro" = { cores = 1; memory = 1024; allowsEbsOptimized = false; supportsNVMe = false;};
  "t2.nano" = { cores = 1; memory = 512; allowsEbsOptimized = false; supportsNVMe = false;};
  "t2.small" = { cores = 1; memory = 2048; allowsEbsOptimized = false; supportsNVMe = false;};
  "t2.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = false; supportsNVMe = false;};
  "t3.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3.large" = { cores = 2; memory = 8192; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3.medium" = { cores = 2; memory = 4096; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3.micro" = { cores = 2; memory = 1024; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3.nano" = { cores = 2; memory = 512; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3.small" = { cores = 2; memory = 2048; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3a.2xlarge" = { cores = 8; memory = 32768; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3a.large" = { cores = 2; memory = 8192; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3a.medium" = { cores = 2; memory = 4096; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3a.micro" = { cores = 2; memory = 1024; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3a.nano" = { cores = 2; memory = 512; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3a.small" = { cores = 2; memory = 2048; allowsEbsOptimized = true; supportsNVMe = false;};
  "t3a.xlarge" = { cores = 4; memory = 16384; allowsEbsOptimized = true; supportsNVMe = false;};
  "t4g.2xlarge" = { allowsEbsOptimized = true; cores = 8; memory = 32768; supportsNVMe = false; };
  "t4g.large" = { allowsEbsOptimized = true; cores = 2; memory = 8192; supportsNVMe = false; };
  "t4g.medium" = { allowsEbsOptimized = true; cores = 2; memory = 4096; supportsNVMe = false; };
  "t4g.micro" = { allowsEbsOptimized = true; cores = 2; memory = 1024; supportsNVMe = false; };
  "t4g.nano" = { allowsEbsOptimized = true; cores = 2; memory = 512; supportsNVMe = false; };
  "t4g.small" = { allowsEbsOptimized = true; cores = 2; memory = 2048; supportsNVMe = false; };
  "t4g.xlarge" = { allowsEbsOptimized = true; cores = 4; memory = 16384; supportsNVMe = false; };
  "x1.16xlarge" = { cores = 64; memory = 999424; allowsEbsOptimized = true; supportsNVMe = false;};
  "x1.32xlarge" = { cores = 128; memory = 1998848; allowsEbsOptimized = true; supportsNVMe = false;};
  "x1e.16xlarge" = { cores = 64; memory = 1998848; allowsEbsOptimized = true; supportsNVMe = false;};
  "x1e.2xlarge" = { cores = 8; memory = 249856; allowsEbsOptimized = true; supportsNVMe = false;};
  "x1e.32xlarge" = { cores = 128; memory = 3997696; allowsEbsOptimized = true; supportsNVMe = false;};
  "x1e.4xlarge" = { cores = 16; memory = 499712; allowsEbsOptimized = true; supportsNVMe = false;};
  "x1e.8xlarge" = { cores = 32; memory = 999424; allowsEbsOptimized = true; supportsNVMe = false;};
  "x1e.xlarge" = { cores = 4; memory = 124928; allowsEbsOptimized = true; supportsNVMe = false;};
  "z1d.12xlarge" = { cores = 48; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "z1d.2xlarge" = { cores = 8; memory = 65536; allowsEbsOptimized = true; supportsNVMe = true;};
  "z1d.3xlarge" = { cores = 12; memory = 98304; allowsEbsOptimized = true; supportsNVMe = true;};
  "z1d.6xlarge" = { cores = 24; memory = 196608; allowsEbsOptimized = true; supportsNVMe = true;};
  "z1d.large" = { cores = 2; memory = 16384; allowsEbsOptimized = true; supportsNVMe = true;};
  "z1d.metal" = { cores = 48; memory = 393216; allowsEbsOptimized = true; supportsNVMe = true;};
  "z1d.xlarge" = { cores = 4; memory = 32768; allowsEbsOptimized = true; supportsNVMe = true;};
}
