name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v8
      - name: Build
        run: 'nix-build -I nixpkgs=channel:nixos-20.03 --quiet release.nix -A nixops-aws.x86_64-linux'
  # Run black v19.10b0 and ensure no diff, using a pinned channel to ensure the
  # build doesn't break when the version of black on the release channel
  # upgrades. The specific commit is not special; just a commit from the
  # nixpkgs-unstable channel that deterministically provides the Black v19.10b0,
  # which as of this writing is the latest version.
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v8
      - name: Black
        run: 'nix-shell ./shell.nix --run "black --check ."'
